apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver-deployment
  labels:
    app: nodeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
      - name: nodeserver
        image: siegfriedschmidt/videostreamerapp:nodeserver
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                key: node_env
                name: nodeserver-config
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: nodeserver-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nodeserver-service
spec:
  type: NodePort
  selector:
    app: nodeserver
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001